# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  create:
    tags: [ "v*" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ ubuntu-latest, macos-13, windows-2022 ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Variables
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          system=$(uname -s | tr '[:upper:]' '[:lower:]')
          architecture=$(uname -m | tr '[:upper:]' '[:lower:]')
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0")
          artifact_filename="fortify-${tag}-${system}-${architecture}"
          echo "Artifact Filename: $artifact_filename"
          echo "ArtifactTag=$tag" >> $GITHUB_ENV
          echo "ArtifactFilename=$artifact_filename" >> $GITHUB_ENV

      - name: Setup Variables on Windows
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          $system = "windows"
          $architecture = $env:PROCESSOR_ARCHITECTURE.ToLower()
          $tag = git describe --tags --abbrev=0 2>$null
          if ($LASTEXITCODE -ne 0) {
            $tag = "v0"
            $LASTEXITCODE = 0
          }
          $artifact_filename = "fortify-${tag}-${system}-${architecture}"
          Write-Host "Artifact Filename: $artifact_filename"
          echo "ArtifactTag=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ArtifactFilename=$artifact_filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v ./...

      - name: Build
        #run: go build -v ./...
        run: go build -ldflags "-s -w" -v -o ./${{ env.ArtifactFilename }}

      - name: Upload
        if: ${{ env.ArtifactTag != 'v0' }}
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: ${{ env.ArtifactFilename }}
          path: ${{ github.workspace }}/${{ env.ArtifactFilename }}
