name: Release

on:
  push: { branches: [ "main" ], tags: [ "v*" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: true
    uses: ./.github/workflows/build.yml
    with:
      os: '${{ matrix.os }}'
      go-version: '${{ matrix.go }}'
  ##build
  release:
    needs: [ build ]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: { path: /tmp/artifacts, pattern: '*' }
      - run: ls -lhAR /tmp/artifacts
      - name: Release ${{ github.ref }}
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN_FOR_RELEASE }}
          files: "/tmp/artifacts/**/*"
          fail_on_unmatched_files: false
  ##release
##jobs
